- name: Create directory
  file:
    path: "{{ influxdb_path }}"
    state: directory

- name: Template InfluxDB configuration
  template:
    src: influxdb.env.j2
    dest: "{{ influxdb_path }}/influxdb.env"
    mode: "600"

- name: Template Docker Compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{ influxdb_path }}/docker-compose.yml"

- name: Start InfluxDB
  community.general.docker_compose:
    project_src: "{{ influxdb_path }}"
    state: present
  register: output
